name: nmd-variant-effect-prediction
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python >=3.12
  - tqdm >=4.66.5,<5
  # packages required for development
  - pytest >=8.3.3,<9
  - pytest-cov >=5.0.0,<6
  - pytest-mock >=3.14.0,<4
  - pytest-sugar >=1.0.0,<2
  # other dependencies
  - importlib-metadata
  - pandas
  - numpy
  - pyfaidx
  - biopython
  - pyranges
  - pandas-stubs
